# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, convertible, libdevil, primitive, QuickCheck, ratioInt
, testFramework, testFrameworkQuickcheck2, transformers, vector
}:

cabal.mkDerivation (self: {
  pname = "friday";
  version = "0.1.1";
  sha256 = "1mzh5d4ddmnslbwya2mgld4smipndn686aia5fx9d07kbvgfxyb3";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    convertible primitive ratioInt transformers vector
  ];
  testDepends = [
    QuickCheck testFramework testFrameworkQuickcheck2 vector
  ];
  doCheck = false;
  extraLibraries = [ libdevil ];
  meta = {
    homepage = "https://github.com/RaphaelJ/friday";
    description = "A functionnal image processing library for Haskell";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
