# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, filepath }:

cabal.mkDerivation (self: {
  pname = "FindBin";
  version = "0.0.5";
  sha256 = "197xvn05yysmibm1p5wzxfa256lvpbknr5d1l2ws6g40w1kpk717";
  buildDepends = [ filepath ];
  meta = {
    homepage = "https://github.com/audreyt/findbin";
    description = "Locate directory of original program";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
