# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, HUnit, ImageMagick, liftedBase
, MonadCatchIOTransformers, QuickCheck, resourcet, systemFilepath
, testFramework, testFrameworkHunit, testFrameworkQuickcheck2, text
, transformers, vector
}:

cabal.mkDerivation (self: {
  pname = "imagemagick";
  version = "0.0.3.5";
  src = /Users/joelteon/.dev/Haskell/imagemagick-0.0.3.5;
  isLibrary = true;
  isExecutable = true;
  doCheck = false;
  buildDepends = [
    MonadCatchIOTransformers resourcet systemFilepath text transformers
    vector
  ];
  testDepends = [
    HUnit ImageMagick liftedBase QuickCheck resourcet
    systemFilepath testFramework testFrameworkHunit
    testFrameworkQuickcheck2 text transformers vector
  ];
  buildFlags = "-v3";
  pkgconfigDepends = [ ImageMagick ];
  meta = {
    description = "bindings to imagemagick library";
    license = "unknown";
    platforms = self.ghc.meta.platforms;
  };
})
