# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, blazeMarkup, hamlet, shakespeare, text, time
, xmlConduit, yesodCore
}:

cabal.mkDerivation (self: {
  pname = "yesod-newsfeed";
  version = "1.2.0.2";
  sha256 = "1ayrhhavx1v9ys7489rddapkilsbm8vx5khv2sxfhg2c7xypdfjc";
  buildDepends = [
    blazeHtml blazeMarkup hamlet shakespeare text time xmlConduit
    yesodCore
  ];
  meta = {
    homepage = "http://www.yesodweb.com/";
    description = "Helper functions and data types for producing News feeds";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
