include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = security_cssm

security_cssm_HEADER_FILES = $(notdir $(wildcard lib/*.h))
security_cssm_HEADER_FILES_DIR = lib

security_cssm_CC_FILES = lib/guids.cpp

include $(GNUSTEP_MAKEFILES)/library.make
