[
  "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
  "/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI"
  "/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit"
  "/usr/lib/libbsm.0.dylib"
  "/usr/lib/libc++.1.dylib"
  "/usr/lib/libc++abi.dylib"
  "/usr/lib/libexpat.1.dylib"
  "/usr/lib/libicucore.A.dylib"
  "/usr/lib/libz.1.dylib"
]
