# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, base16Bytestring, binary, cmdlib, cryptohash
, curl, dataenc, dataOrdlist, datetime, extensibleExceptions
, filepath, FindBin, hashable, haskeline, html, HTTP, HUnit, mmap
, mtl, network, parsec, QuickCheck, random, regexCompatTdfa
, shellish, split, tar, terminfo, testFramework, testFrameworkHunit
, testFrameworkQuickcheck2, text, unixCompat, utf8String, vector
, zipArchive, zlib

, fetchurl
}:

cabal.mkDerivation (self: {
  pname = "darcs";
  version = "2.9.9";
  src = fetchurl {
    url = "http://darcs.net/reviewed/reviewed.zip";
    sha256 = "0qms9388k6mbc0mjmdw3ps8xl68vcw5zkrcfdm7mliagd0zd3hdy";
  };
  isLibrary = true;
  isExecutable = true;
  doCheck = false;
  buildDepends = [
    attoparsec base16Bytestring binary cryptohash dataenc dataOrdlist
    datetime extensibleExceptions filepath hashable haskeline html HTTP
    mmap mtl network parsec random regexCompatTdfa tar terminfo text
    unixCompat utf8String vector zipArchive zlib
  ];
  testDepends = [
    binary cmdlib dataenc extensibleExceptions filepath FindBin html
    HUnit mmap mtl parsec QuickCheck regexCompatTdfa shellish split
    testFramework testFrameworkHunit testFrameworkQuickcheck2 text
    unixCompat zipArchive zlib
  ];
  extraLibraries = [ curl ];
  postInstall = ''
    mkdir -p $out/etc/bash_completion.d
    mv contrib/darcs_completion $out/etc/bash_completion.d/darcs
  '';
  meta = {
    homepage = "http://darcs.net/";
    description = "a distributed, interactive, smart revision control system";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
    maintainers = [ self.stdenv.lib.maintainers.andres ];
  };
})
