# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal }:

cabal.mkDerivation (self: {
  pname = "ratio-int";
  version = "0.1.2";
  sha256 = "06kqr4iyi184sa8y2vdkw5h0pvh5f8lwcqb8mbcn34lpqm961s7g";
  meta = {
    homepage = "https://github.com/RaphaelJ/ratio-int";
    description = "Fast specialisation of Data.Ratio for Int.";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
